name: CI
on:
  push:
  pull_request:
    types:
    - edited
    - opened
    - reopened
    - synchronize
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@master
    - name: Install dependencies
      run: |
        sudo npm install jsonlint markdownlint-cli -g
    - name: Lint Markdown/JSON files
      shell: pwsh
      run: |
        ./lint.ps1
    - name: Verify code integrity
      run: |
        peverify Code/Assembly-CSharp.dll --verify metadata
